# used for deployment using docker swarm or docker compose
version: "3.8"
services:
  frontend:
    build: ./frontend/spring-petclinic-angular
    image: anassumrani/frontend:latest
    ports:
    - target: 4200
      published: 4200
      protocol: tcp
    depends_on:
    - backend
  backend:
    image: anassumrani/backend:latest
    ports:
    - target: 9966 
      published: 9966
      protocol: tcp
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    volumes:
      - type: bind
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
    - frontend
    - backend
