---
# tasks file for docker-compose-build
- name: Google jib docker backend image
  shell: |
   cd backend && cd spring-petclinic-rest && mvn compile jib:build -X -DjibSerialize=true -Djib.to.auth.username={{USERNAME}} -Djib.to.auth.password={{PASSWORD}}

- name: Docker compose build frontend image
  shell: |
   docker-compose build 


