---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: anassumrani/backend:latest
        ports:
        - containerPort: 9966
       