---
- name: check if aws is installed
  shell: |
    aws --version || true
  register: aws_installed
  ignore_errors: yes

- name: check output of aws_installed
  debug:
    msg: "{{ aws_installed }}"

- name: install aws-cli
  shell: |
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
  when: "'aws' not in aws_installed.stdout"

- name: installing eksctl
  shell: curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"| tar xz -C /tmp && sudo mv /tmp/eksctl /usr/local/bin